/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#ffafd2",
        "primary": "#ae1e75",
        "on-primary-container": "#ffffff",
        "surface-tint": "#ae1f75",
        "outline": "#8b7078",
        "background": "#fef8fa",
        "on-tertiary-fixed-variant": "#7b008f",
        "inverse-on-surface": "#f5eff1",
        "on-tertiary-container": "#ffffff",
        "on-background": "#1d1b1d",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "surface-variant": "#e7e1e3",
        "tertiary-fixed-dim": "#f9abff",
        "surface-container-low": "#f8f2f4",
        "on-surface": "#1d1b1d",
        "surface-container-high": "#ece7e9",
        "on-error-container": "#93000a",
        "tertiary-container": "#b743c9",
        "inverse-surface": "#323031",
        "secondary": "#725478",
        "on-tertiary-fixed": "#35003f",
        "surface-container-highest": "#e7e1e3",
        "tertiary": "#9a24ae",
        "primary-container": "#ce3c8f",
        "on-primary": "#ffffff",
        "on-surface-variant": "#584048",
        "secondary-fixed": "#fbd7ff",
        "surface-dim": "#ded9db",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#dfbbe4",
        "surface-container": "#f2ecee",
        "on-primary-fixed": "#3d0025",
        "primary-fixed": "#ffd8e7",
        "on-secondary-container": "#76587c",
        "on-secondary-fixed-variant": "#583d5f",
        "on-primary-fixed-variant": "#8b005b",
        "secondary-container": "#f9d4fe",
        "inverse-primary": "#ffafd2",
        "error-container": "#ffdad6",
        "surface-bright": "#fef8fa",
        "outline-variant": "#dfbec8",
        "on-secondary-fixed": "#2a1231",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#ffd6fe",
        "surface": "#fef8fa"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"]
      }
    },
  },
  plugins: [],
}